#ÅäÖÃÊı¾İÔ´
spring:
  datasource:
     url: jdbc:mysql://127.0.0.1:3306/user?useUnicode=true&characterEncoding=utf8&useSSL=false
     username: root
     password: sutao
     driver-class-name: com.mysql.jdbc.Driver